### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by arkjun** [mohwa/seogi#3]
The license file is missing. (ex. license or license.txt license.md...)

ref:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

I guess it's an MIT license from the contents of the package.json file. right?

Thanks.

**Comment by mohwa** [comment]
@rkJun

That's right and i will update license file as soon ~ 😄

**Comment by mohwa** [comment]
@rkJun  

I was added LICENSE file for the project and you can confirm at that url(https://github.com/mohwa/seogi/blob/master/LICENSE.md)
